CREATE DATABASE almacen;
USE almacen;


CREATE TABLE ALMACEN (
    ID_MARCAS VARCHAR(20),
    TIPO VARCHAR(20), 
    SABOR VARCHAR(20), 
    ENVASE VARCHAR(20), 
	PESO VARCHAR (20),
    PRECIO INT 
);

INSERT INTO ALMACEN (ID_MARCAS, TIPO, SABOR, ENVASE, PESO, PRECIO)
VALUES
('RIERA','SEMILLAS','CHIA','BOLSA','250GR',300),
('RIERA','SEMILLAS','LINO','BOLSA','500GR',500),
('RIERA','SEMILLAS','GIRASOL','BOLSA','1000GR',800),
('ARCOR','MERMELADA','FRUTILLA','FRASCO','400GR',450),
('ARCOR','MERMELADA','DURAZNO','FRASCO','400GR',450),
('ARCOR','MERMELADA','NARANJA','FRASCO','400GR',450),
('ARCOR','MERMELADA','FRUTOS ROJOS','FRASCO','400GR',450),
('NOEL','MERMELADA','DURAZNO','FRASCO','400GR',380),
('LIMAY','MERMELADA','DURAZNO','FRASCO','400GR',350),
('NOEL','MERMELADA','FRUTILLA','FRASCO','400GR',380),
('INCA','HIERBA','ALOE VERA','BOLSA','500GR',400),
('INCA','HIERBA','ARANDANO','BOLSA','500GR',400),
('INCA','HIERBA','SOJA','BOLSA','500GR',400),
('INCA','HIERBA','VALERIANA','BOLSA','500GR',400);


SELECT * FROM almacen;


ALTER TABLE ALMACEN 
ADD COLUMN ID INT NOT NULL #CREA LA COLUMNA DE NUMEROS ENTEROS
auto_increment PRIMARY KEY FIRST;  #le digo a sql que rellene los numeros solos y define la llave principal first mueve al extremo izquierdo de la tabla


alter table ALMACEN RENAME TO MERCADERIA;


SELECT ID_MARCAS, TIPO, SABOR FROM MERCADERIA WHERE PESO = '400GR';


SET SQL_SAFE_UPDATES = 0;
 UPDATE MERCADERIA SET PRECIO = PRECIO + 200 WHERE ID_MARCAS = 'ARCOR';

SET SQL_SAFE_UPDATES = 1;


SELECT * FROM MERCADERIA ORDER BY PRECIO ASC;


SET SQL_SAFE_UPDATES = 0;               #ES UN COMANDO PARA SACAR EL SEGURO DE SQL QUE PROHIBE EJECUTAR COMANDOS COMO UPDATE DELETE DEBES USAR LA PRIMARY KEY 
DELETE FROM MERCADERIA WHERE PESO = '500GR' OR PESO = '1000GR';
SET SQL_SAFE_UPDATES = 1;


SELECT * FROM MERCADERIA;